Config = {}

Config.Max_Items = 5000
Config.Max_Weapons = 10

Config.Language = {
    [0] = {text = "Pick up",},
    [1] = {text = "Gold",},
    [2] = {text = "Money",},
    [3] = {text = "Accept",},
    [4] = {text = "How much money you need transfer",},
    [5] = {text = "How much gold you need transfer",},
    [6] = {text = "How much items you need transfer",},
    [7] = {text = "You cant transfer equiped weapon",},
    [8] = {text = "You dont have slots in inventory",},
    [10] = {text = "Inventory",},
    [11] = {text = "You not hold any weapon for show",},
    [12] = {text = "You equip first revolver.",},
    [13] = {text = "You equip second revolver.",},
    [14] = {text = "You have equiped 2 revolvers.",},
    [15] = {text = "You equip main weapon.",},
    [16] = {text = "You equip main second weapon.",},
    [17] = {text = "You have equiped 2 weapons.",},
    [18] = {text = "You equip addon item.",},
    [19] = {text = "You put down second revolver.",},
    [20] = {text = "You put down first revolver.",},
    [21] = {text = "You put down addon item.",},
    [22] = {text = "You put down first rifle.",},
    [23] = {text = "You put down second rifle.",},
    [24] = {text = "Busket with items",},
    [25] = {text = "Busket with gild",},
    [26] = {text = "Moneys",},
    [27] = {text = "Box with ",},
    [28] = {text = "Give hand ",},
    [29] = {text = "Give slap ",},
    [30] = {text = "You dont have this count in inventory.",},
    [31] = {text = "Wrong value.",},
    [32] = {text = "First you must unequip your weapon.",},
    [33] = {text = "You dont have this count in inventory.",},
    [34] = {text = "You dont have this money.",},
    [35] = {text = "You dont have this gold.",},
    [36] = {text = "You cant drop equiped weapon.",},
    [37] = {text = "You cant drop items near other items.",},
    [38] = {text = "This inventory is not created.",},
    [39] = {text = "This inventory is opened from other.",},
    [40] = {text = "You dont have this count money.",},
    [41] = {text = "You dont have slots in inventory.",},
    [42] = {text = "He cant hold much items",},
    [43] = {text = "He cant hold more weapons.",},
    [44] = {text = "You cant hold more weapons.",},
    [45] = {text = "You must unequip first second weapon.",},
    [46] = {text = "Inventory storage is opened. But player is not active try again.",},
}