var config = {}
config.language = [
    {text:"Items"},
    {text:"Armes"},
    {text:"Coffre"},
    {text:"Slots"},
    {text:"Tenues"},
    {text:"Chapeau"},
    {text:"Lunettes"},
    {text:"Masque"},
    {text:"Bandana"},
    {text:"Écharpe"},
    {text:"Cape ou Poncho"},
    {text:"Chemise"},
    {text:"Gilet"},
    {text:"Manteau"},
    {text:"Munitions, Accessoires, Dos"},
    {text:"Bagues"},
    {text:"Gants"},
    {text:"Gantelets"},
    {text:"Ceinture, étui etc."},
    {text:"Bretelles"},
    {text:"Chaps, Pantalon"},
    {text:"Bottes"},
    {text:"Argent"},
    {text:"Dollars."},
    {text:"Pépite d'or"},
    {text:"Or."},
    {text:"Équipé"},
    {text:"Non équipé"},//27
    {text:"Fermer"},//28
    {text:"Inventaire"},
    {text:"Donner"},
    {text:"Jetter"},
    {text:"manches"},
]

