var config = {}
config.language = [
    {text:"Items"},
    {text:"Weapons"},
    {text:"Storage"},
    {text:"Slots"},
    {text:"Outfiit manage"},
    {text:"Wear or unwear hat"},
    {text:"Wear or unwear glass"},
    {text:"Wear or unwear mask"},
    {text:"Wear or unwear bandana"},
    {text:"Wear or unwear scarf"},
    {text:"Wear or unwear cloak or poncho"},
    {text:"Wear or unwear shirt"},
    {text:"Wear or unwear vest"},
    {text:"Wear or unwear coat"},
    {text:"Wear or unwear ammo, accesories, backs"},
    {text:"Wear or unwear rings"},
    {text:"Wear or unwear gloves"},
    {text:"Wear or unwear gauntlets"},
    {text:"Wear or unwear belt, holster etc."},
    {text:"Wear or unwear suspenders"},
    {text:"Wear or unwear chaps, pants"},
    {text:"Wear or unwear boots"},
    {text:"Money"},
    {text:"Currency for pay."},
    {text:"Gold"},
    {text:"Currency for pay."},
    {text:"Equiped"},
    {text:"Unequiped"},
    {text:"Close"},//28
    {text:"Inventory"},
    {text:"Give"},
    {text:"Drop"},
]
